#pragma once

#include "ImageManager.h"
#include "supportingFunctional.h"

#define PLAYER_IMAGE "player.png"
#define ICICLE_IMAGE "icicle.png"
#define ICICLE_SECOND_IMAGE "icicle2.png"
#define ICICLE_THIRD_IMAGE "icicle3.png"
#define SPIDER_IMAGE "spider.png"
#define SPIDER_DEAD_IMAGE "spider_dead.png"
#define FRAGMENT_IMAGE "fragment.png"

#define NORMAL_GRAVITY Vec2(0,-500)
#define HEADER_HEIGHT 150


#define FRAGMENT_SIZE Size(15,15)

#define ICICLE_SPAWN_INTERVAL 1.0
#define ICICLE_APPEARANCE_TIME 3.0
#define ICICLE_COLUMN_RELEASE_TIME 0.5
#define ICICLE_DIE_EFFECT_DURATION 0.3
#define ICICLE_HEALTH 200

#define SHOT_SPAWN_INTERVAL 0.1
#define SHOT_APPEARANCE_TIME 0.1
#define SHOT_VERTICAL_VELOCITY 700
#define SHOT_SIZE Size(10,17)
#define SHOT_HEALTH 1

#define SPIDER_SPAWN_INTERVAL 10.0
#define SPIDER_APPEARANCE_TIME 2.0
#define SPIDER_COLUMN_RELEASE_TIME 0.5
#define SPIDER_HEALTH 300
#define SPIDER_FALL_TIME 2.5

#define SPIDER_WEB_LENGHT_MIN 50
#define SPIDER_WEB_LENGHT_MAX 250
#define SPIDER_WEB_WIDTH_SCALE 0.33

// Ceinilg
#define CEILING_COLLISION_MASK 2
#define CEILING_CATEGORY 1
#define CEILING_TEST 2
#define CEILING_TAG 300
#define CEILING_BODY_INFO BodyInfo{CEILING_CATEGORY, CEILING_COLLISION_MASK, CEILING_TEST, CEILING_TAG}
// Edge
#define EDGE_COLLISION_MASK 2
#define EDGE_CATEGORY 1
#define EDGE_TEST 2
#define EDGE_TAG 200
#define EDGE_BODY_INFO BodyInfo{EDGE_CATEGORY, EDGE_COLLISION_MASK, EDGE_TEST, EDGE_TAG}
// Footer
#define FOOTER_COLLISION_MASK 2
#define FOOTER_CATEGORY 1
#define FOOTER_TEST 2
#define FOOTER_TAG 100
#define FOOTER_BODY_INFO BodyInfo{FOOTER_CATEGORY, FOOTER_COLLISION_MASK, FOOTER_TEST, FOOTER_TAG}
// Player
#define PLAYER_COLLISION_MASK 1
#define PLAYER_CATEGORY 3
#define PLAYER_TEST 1
#define PLAYER_TAG 1
#define PLAYER_BODY_INFO BodyInfo{PLAYER_CATEGORY, PLAYER_COLLISION_MASK, PLAYER_TEST, PLAYER_TAG}
// Icicle
#define ICICLE_COLLISION_MASK 1
#define ICICLE_CATEGORY 3
#define ICICLE_TEST 1
#define ICICLE_TAG 1100
#define ICICLE_TAG_TO 1150
#define ICICLE_BODY_INFO BodyInfo{ICICLE_CATEGORY, ICICLE_COLLISION_MASK, ICICLE_TEST, ICICLE_TAG}
#define IS_ICICLE(tag) Range{ICICLE_TAG,ICICLE_TAG_TO}.contains(tag)
// Spyder
#define SPIDER_COLLISION_MASK 1
#define SPIDER_CATEGORY 3
#define SPIDER_TEST 1
#define SPIDER_TAG 1200
#define SPIDER_TAG_TO 1250
#define SPIDER_BODY_INFO BodyInfo{SPIDER_CATEGORY, SPIDER_COLLISION_MASK, SPIDER_TEST, SPIDER_TAG}
#define IS_SPIDER(tag) Range{SPIDER_TAG,SPIDER_TAG_TO}.contains(tag)
// Shot
#define SHOT_COLLISION_MASK 1
#define SHOT_CATEGORY 3
#define SHOT_TEST 1
#define SHOT_TAG 1300
#define SHOT_TAG_TO 1350
#define SHOT_BODY_INFO BodyInfo{SHOT_CATEGORY, SHOT_COLLISION_MASK, SHOT_TEST, SHOT_TAG}
#define IS_SHOT(tag) Range{SHOT_TAG,SHOT_TAG_TO}.contains(tag)
// Fragment
#define FRAGMENT_COLLISION_MASK 1
#define FRAGMENT_CATEGORY 3
#define FRAGMENT_TEST 1
#define FRAGMENT_TAG 1400
#define FRAGMENT_TAG_TO 1450
#define FRAGMENT_BODY_INFO BodyInfo{FRAGMENT_CATEGORY, FRAGMENT_COLLISION_MASK, FRAGMENT_TEST, FRAGMENT_TAG}
#define IS_FRAGMENT(tag) Range{FRAGMENT_TAG,FRAGMENT_TAG_TO}.contains(tag)
